### PR TITLE
Added another ping message

### PR DESCRIPTION
**Pull request by AWonkeyTortila**

### CODE REVIEW

**Comment by AWonkeyTortila** [comment]
5 G - No Life

**Comment by RainaXA** [comment]
I can't actually accept this in because of the caps in Waifu (that command will never get triggered), and the ping message will never show up either.
(do you also intend on having it only trigger when there's no arguments? If so, you may want to change it to "if(!args)"

Metaverse in North America?!?!??!?

**Comment by AWonkeyTortila** [comment]
1. So I change it from 'Waifu' to 'waifu'?
2. No, I just want it to be a simple 'Call -> Answer' cmd
3. Yes ;)

**Comment by RainaXA** [comment]
1. yes
2. then !args
3. yes

**Pull request closed without merging**
