### PR TITLE
Wonkey's cornder

### PR DESCRIPTION
**Pull request by AWonkeyTortila**
Made a crappy website for documentation :P

### CODE REVIEW

**Comment by AWonkeyTortila** [comment]
She won't let me see my kids.

**Review by RainaXA — CHANGES_REQUESTED** [review]
This won't crash the bot, but the message will never show up without a change in the number on line 396. I'll approve it if that gets done haha

**Comment by AWonkeyTortila** [comment]
Added by one

**Comment by RainaXA** [comment]
the site is broken on my phone but I'm sure that's just an issue with mobile lol either way it's sick :)

**Pull request merged**
